# Generated by Django 5.2.11 on 2026-02-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='news/'),
        ),
    ]
